#spring.datasource.url=jdbc:postgresql://localhost:5432/plant_app
#spring.datasource.username=plant_user
#spring.datasource.password=planted
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/plant_db
    username: plant_user
    password: planted
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  database: postgresql
  database-platform: org.hibernate.dialect.PostgreSQLDialect